server:
  port: 11000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
      - id: customer-server
        uri: lb://customer
        predicates:
          - Path=/customer/**
        filters:
          - StripPrefix=1
      - id: provider-server
        uri: lb://provider
        predicates:
          - Path=/provider/**
        filters:
          - StripPrefix=1
      enabled: true




